### ISSUE TITLE
Document flex volumes on Packet

### ISSUE THREAD

**Issue by vielmetti** [appscode-cloud/pharmer#381]
I see that there's a flex volumes package for Pharmer for Packet's block storage, but I'm not finding any documentation (and there probably should be some). Happy to help.

References
* https://www.packet.net/bare-metal/services/storage/
* https://www.packet.net/developers/api/volumeattachments/
* https://github.com/packethost/packet-block-storage

Cross reference with https://github.com/packethost/packet-block-storage/issues/17

**Comment by tamalsaha** [comment]
Obsolete.
